title: Hello, world! I'm Micael Grilo
description: > # this means to ignore newlines until "baseurl:"
  Micael F. Grilo, Python Software Engineer at Lisbon.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Micael F. Grilo # add your name
author-img: micael-grilo.jpeg # add your photo
about-author: There are 10 types of people in this world. Those who understand binary and those who don’t. # add description
social-twitter: micael_grilo # add your Twitter handle
social-facebook: false # add your Facebook handle
social-github: micael-grilo # add your Github handle
social-linkedin: micael-grilo # add your Linkedin handle
social-email: micael.grilo@outlook.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
